spring.application.name=app
spring.datasource.url=jdbc:${NEON_DATABASE_URL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect